### ISSUE TITLE
Remember User Selections

### ISSUE THREAD

**Issue by solita-anttihu** [thermoweb/encrypt-string-plugin#1]
Hello,

It would be great if the Encrypt/Decrypt dialog would remember user selections for the algorithm dropdown and "surrounded by ENC(...)" checkbox. Usually a project has agreed what values need to use for these, so it would be helpful if the user did not need to make the choices every time in the dialog.

**Comment by thermoweb** [comment]
Ok, I think this sound like a good idea. I'll look into it to see if it's doable. The question is the time :)

sorry for the late answer, I did not get any notification :'(

**Comment by thermoweb** [comment]
I finally done it today. I uploaded it to the marketplace, it should be available in two days may be.
